### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by kieth1205** [55Builds/Flutter-FFNavigationBar#2]
I think this library has alignment errors as you can see in the image, and it's dragged to the left. I have tried it on my phone and on the virtual machine.
![image](https://user-images.githubusercontent.com/45708339/69547344-fc0f6f80-0fc7-11ea-9fa9-3179f358f539.png)

**Comment by jwbaldry** [comment]
Can you paste up the entire `lib/main.dart` file or provide a link?  

I've updated the README.md with new (simpler) Scaffold code block which appears to work fine on device and emulator/simulator based on the current 0.0.1 version.

**Comment by janlektonen** [comment]
Hi - I also have found a problem with the border color on each circle avatar. If you change the background to Black like: "barBackgroundColor: Colors.black87" then there is a black border around each selected Circle avatar and I've tried all I know to change this color. Is there a way to change border color on selecteditem circle from black to any other color ?

![Screenshot 2019-11-26 at 12 06 23](https://user-images.githubusercontent.com/25502842/69624633-60bcdf80-1045-11ea-83a5-c7a7bb8d6dbd.png)

**Comment by jwbaldry** [comment]
Hi @janlektonen , the border for the tab items is taken to be the same as the bar background colour.  In your case, using black87 means using colour with opacity, so the result is a border for the tab item also with the same opacity, meaning a double layer of black87 colour (which results in the deep black appearance).  

I'll post up a new version soon under a new issue with the ability to explicitly set a **selectedItemBorderColor** in the theme, which you can use to override the colour.  

This would allow you to specify the border colour as transparent to hide the border or specify a separate border colour.  

Sadly it will not support using an opaque border colour without creating the problem of revealing the bar background colour which sits underneath it.

**Comment by Jaydub55** [comment]
@janlektonen ... version 0.1.2 is now available which provides an option to specify the border colour for the selected item. I hope that helps meet your requirements.

**Comment by janlektonen** [comment]
That is fantastic :-) I can see the documention and will try it out now and give you feedback.
Thank you very much @Jaydub55

**Comment by janlektonen** [comment]
It works fine :-)

**Comment by Jaydub55** [comment]
@kieth1205 ... any luck with providing some sample source that illustrates the alignment issue?
