### ISSUE TITLE
Alert notification on FFNavigationBarItem

### ISSUE THREAD

**Issue by joshuafriso** [55Builds/Flutter-FFNavigationBar#7]
I trying to insert a little circle on the icon on FFNavigationBarItem when I have new messages but I can´t do this. Any idea about this or it's just not possible?
![image](https://user-images.githubusercontent.com/17890321/70543596-66d4b500-1b49-11ea-8e87-4d7fd3aaf96b.png)
Something like this

**Comment by Jaydub55** [comment]
Hey @joshuafriso, 
At the moment it doesn't have the option to display a notification badge on the bottom bar items.

You could add your own into the source of FFNavigationBarItem within the `Stack` or potentially by using another plugin like [Badges](https://pub.dev/packages/badges) which is pretty useful for wrapping elements for this purpose.

I've logged as an enhancement and will work on adding the capability as it will provide a benefit to other users but it may be a couple of days until I have a window to look at finishing it.

**Comment by joshuafriso** [comment]
Hi,

I did a little change and now it's working with or without badge necessity 

![FFNavigationBarItemWithBadge](https://user-images.githubusercontent.com/17890321/70572570-cbf6cd80-1b7e-11ea-8a98-a6ec30b423da.jpeg)
